headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "C:\\PedroTiago\\02_Desenvolvimento\\Projetos\\Site_Principal\\functions"
functionsDirectoryOrigin = "config"

[dev]
command = "npm run dev"
port = 3000.0
publish = "dist"

[functions]

[functions."*"]
node_bundler = "esbuild"

[build]
publish = "C:\\PedroTiago\\02_Desenvolvimento\\Projetos\\Site_Principal\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\PedroTiago\\02_Desenvolvimento\\Projetos\\Site_Principal\\functions"

[build.environment]
NODE_VERSION = "18"
NPM_VERSION = "9"
REACT_APP_SITE_URL = "https://pedrotiagocontabilidade.netlify.app"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Strict-Transport-Security = "max-age=31536000; includeSubDomains"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.pedrotiagocontabilidade.com.br"

[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/contabilidade"
to = "/servicos"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/fiscal"
to = "/servicos"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/consultoria"
to = "/contato"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/*"
to = "/404"
status = 401.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/wp-admin/*"
to = "/404"
status = 401.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/.git/*"
to = "/404"
status = 401.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]