services:
  - type: web
    name: pedro-tiago-contabilidade
    runtime: static
    staticPublishPath: ./dist
    buildCommand: npm ci && npm run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://pedro-tiago-contabilidade.onrender.com
    autoDeploy: true
    rootDir: .
    branch: main
    repo: https://github.com/pedrotiagofaria25-dev/pedro-tiago-contabilidade.git