name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Claude Code Review
        uses: anthropics/claude-code-action@main
        with:
          claude_api_key: ${{ secrets.CLAUDE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          review_type: 'comprehensive'

      - name: Post review results
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '🤖 Claude Code Review completo! Verifique os comentários acima.'
              });
            }